name: phober-backend

x-common-env: &common-env
    APACHE_RUN_USER: "#1000"
    APACHE_RUN_GROUP: "#1000"
    APACHE_LOG_DIR: /var/log/apache2
    APACHE_RUN_DIR: /var/run/apache2
    APACHE_PID_FILE: /var/run/apache2/apache2.pid
    APACHE_LOCK_DIR: /var/lock/apache2
    APP_TIMEZONE: ${APP_TIMEZONE:-Asia/Baku}
    REDIS_CLIENT: predis
    REDIS_HOST: redis
    REDIS_PORT: 6379
    CACHE_STORE: redis
    SESSION_DRIVER: redis
    QUEUE_CONNECTION: redis

x-reverb-env: &reverb-env
    BROADCAST_CONNECTION: reverb
    REVERB_APP_ID: ${REVERB_APP_ID:-phober}
    REVERB_APP_KEY: ${REVERB_APP_KEY:-phober-key}
    REVERB_APP_SECRET: ${REVERB_APP_SECRET:-phober-secret}
    REVERB_HOST: ws
    REVERB_PORT: 8080
    REVERB_SCHEME: http

x-common-healthcheck-v2: &common-healthcheck-v2
    test: [ "CMD", "curl", "-f", "http://localhost/up" ]
    interval: 10m
    retries: 5
    start_period: 10m
    timeout: 1m

x-shared-laravel-volume: &shared-laravel-volume
    ./shared/laravel-common:/var/www/html/shared:ro


services:
    nginx-proxy-manager:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: nginx-proxy-manager
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      volumes:
        - ./docker/npm/data:/data
        - ./docker/npm/letsencrypt:/etc/letsencrypt
      networks:
        - public
        - private

    adminpanel:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: adminpanel
        environment:
            <<: [*common-env, *reverb-env]
            APP_KEY: ${APP_KEY_ADMINPANEL}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-defaultaccesskey}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-defaultsecretkey}
            AWS_DEFAULT_REGION: us-east-1
            AWS_BUCKET: media
            AWS_URL: "${API_GATEWAY_HOST:-https://localhost}:${API_GATEWAY_PORT:-8000}/s3"
            AWS_ENDPOINT: 'http://minio:9000'
            AWS_USE_PATH_STYLE_ENDPOINT: 'true'
            DB_CONFIGS_DATABASE: '/var/www/html/database/configs.sqlite'
        volumes:
            - *shared-laravel-volume
            - ./services/adminpanel:/var/www/html
            - ./docker/sqlite/configs.sqlite:/var/www/html/database/configs.sqlite
        networks:
            - private
            - public
        entrypoint: sh -c "apache2 -D FOREGROUND"

    api-gateway:
        image: nginx:latest
        container_name: api-gateway
        volumes:
            - ./docker/api-gateway/certs/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
            - ./docker/api-gateway/certs/nginx.key:/etc/nginx/ssl/nginx.key:ro
            - ./docker/api-gateway/certs/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
            - ./docker/api-gateway/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/api-gateway/public:/etc/nginx/public:ro
        networks:
            - private
            - public
        depends_on:
            - notification-server
            - auth-server
            - device-service
            - crm-service
            - staff-service

    auth-server:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: auth-server
        environment:
            << : *common-env
            APP_KEY: ${APP_KEY_AUTH_SERVER}
        volumes:
            - *shared-laravel-volume
            - ./services/auth-server:/var/www/html
        networks:
            - private
        entrypoint: sh -c "apache2 -D FOREGROUND"
        healthcheck: *common-healthcheck-v2

    config-server:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: config-server
        environment:
            << : *common-env
            APP_KEY: ${APP_KEY_CONFIG_SERVER}
        volumes:
            - *shared-laravel-volume
            - ./services/config-server:/var/www/html
            - ./docker/sqlite/configs.sqlite:/var/www/html/database/database.sqlite
        networks:
            - private
        entrypoint: sh -c "apache2 -D FOREGROUND"
        healthcheck: *common-healthcheck-v2

    notification-server:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: notification-server
        environment:
            << : *common-env
            APP_KEY: ${APP_KEY_NOTIFICATION_SERVER}
        volumes:
            - *shared-laravel-volume
            - ./services/notification-server:/var/www/html
        networks:
            - private
        entrypoint: sh -c "apache2 -D FOREGROUND"
        healthcheck: *common-healthcheck-v2

    device-service:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: device-service
        environment:
            <<: [*common-env, *reverb-env]
            APP_KEY: ${APP_KEY_DEVICE_SERVICE}
            APP_URL: "/hardware"
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: us-east-1
            AWS_BUCKET: media
            AWS_URL: '/s3/media'
            AWS_ENDPOINT: 'http://minio:9000'
            AWS_USE_PATH_STYLE_ENDPOINT: 'true'
            QUEUE_CONNECTION: database
        volumes:
            - *shared-laravel-volume
            - ./services/device-service:/var/www/html
        networks:
            - private
        deploy:
            replicas: 1
        entrypoint: sh -c "apache2 -D FOREGROUND"
        healthcheck: *common-healthcheck-v2

    crm-service:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: crm-service
        environment:
            << : *common-env
            APP_KEY: ${APP_KEY_CRM_SERVICE}
        volumes:
            - *shared-laravel-volume
            - ./services/crm-service:/var/www/html
        networks:
            - private
        entrypoint: sh -c "apache2 -D FOREGROUND"
        healthcheck: *common-healthcheck-v2

    staff-service:
        image: abdukhaligov/phober-php-apache:1.0.0
        container_name: staff-service
        environment:
            <<: [*common-env, *reverb-env]
            APP_KEY: ${APP_KEY_STAFF_SERVICE}
            QUEUE_CONNECTION: database
        volumes:
            - *shared-laravel-volume
            - ./services/staff-service:/var/www/html
        networks:
            - private
        entrypoint: sh -c "apache2 -D FOREGROUND"
        healthcheck: *common-healthcheck-v2

networks:
    private:
        external: true
        name: phober_private
    public:
        external: true
        name: phober_public
