version: "3.7"

x-common-env: &common-env
    APACHE_RUN_USER: "#1000"
    APACHE_RUN_GROUP: "#1000"
    APACHE_LOG_DIR: /var/log/apache2
    APACHE_RUN_DIR: /var/run/apache2
    APACHE_PID_FILE: /var/run/apache2/apache2.pid
    APACHE_LOCK_DIR: /var/lock/apache2

services:
    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./env/mysql:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
        networks:
            - backend

    phpmyadmin:
        platform: linux/x86_64
        image: phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8900:80"
        networks:
            - backend

    adminpanel:
        build:
            context: ./
            dockerfile: ./env/phober-php_8.1-apache/Dockerfile
        image: phober-php_8.1-apache
        container_name: adminpanel
        ports:
            - "8100:80"
        environment:
            << : *common-env
            APP_URL: "http://localhost:8100"
        volumes:
            - ./adminpanel:/var/www/html
            - ./media:/var/www/html/public/storage/media
            - ./media:/var/www/html/storage/app/public/media
            - ~/.ssh:/home/user/.ssh
            - ~/.config/composer:/root/.composer
        depends_on:
            - db
        networks:
            - backend
        entrypoint: sh -c "composer install --no-cache --ignore-platform-reqs &&
            php /var/www/html/artisan migrate &&
            apache2 -D FOREGROUND"

    config-server:
        image: phober-php_8.1-apache
        container_name: config-server
        ports:
            - "8700:80"
        environment:
            << : *common-env
        volumes:
            - ./config-server:/var/www/html
        depends_on:
            - adminpanel
        networks:
            - backend
        entrypoint: sh -c "composer install --no-cache --ignore-platform-reqs &&
            php /var/www/html/artisan hostname:update 'config-server' &&
            apache2 -D FOREGROUND"

    device-service:
        image: phober-php_8.1-apache
        ports:
            - "8300-8399:80"
        environment:
            << : *common-env
            APP_URL: "http://localhost:8000/hardware"
        volumes:
            - ./device-service:/var/www/html
            - ./media:/var/www/html/public/storage/media:ro
            - ./media:/var/www/html/storage/app/public/media:ro
        depends_on:
            - config-server
            - adminpanel
        networks:
            - backend
        deploy:
            replicas: 3
        entrypoint: sh -c "composer install --no-cache --ignore-platform-reqs &&
            php /var/www/html/artisan config-client:update &&
            php /var/www/html/artisan hostname:update 'device-service' &&
            apache2 -D FOREGROUND"

    notification-server:
        image: phober-php_8.1-apache
        container_name: notification-server
        ports:
            - "8888:80"
        environment:
            << : *common-env
        volumes:
            - ./notification-server:/var/www/html
        depends_on:
            - config-server
            - adminpanel
        networks:
            - backend
        entrypoint: sh -c "composer install --no-cache --ignore-platform-reqs &&
            php /var/www/html/artisan config-client:update &&
            php /var/www/html/artisan hostname:update 'notification-server' &&
            apache2 -D FOREGROUND"

    notification-queue:
        image: phober-php_8.1-apache
        container_name: notification-queue
        command: php artisan queue:work
        environment:
            << : *common-env
        volumes:
            - ./notification-server:/var/www/html
        depends_on:
            - notification-server
        networks:
            - backend

    auth-server:
        image: phober-php_8.1-apache
        container_name: auth-server
        ports:
            - "8500:80"
        environment:
            << : *common-env
        volumes:
            - ./auth-server:/var/www/html
        depends_on:
            - config-server
            - adminpanel
        networks:
            - backend
        entrypoint: sh -c "composer install --no-cache --ignore-platform-reqs &&
            php /var/www/html/artisan config-client:update &&
            php /var/www/html/artisan hostname:update 'auth-server' &&
            apache2 -D FOREGROUND"

    api-gateway:
        image: nginx:latest
        container_name: api-gateway
        ports:
            - "8000:80"
        volumes:
            - ./env/api-gateway/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - backend
        depends_on:
            - config-server
            - auth-server
            - device-service
            - notification-server

    #old-website:
    #    build:
    #        context: ./
    #        dockerfile: ./env/phober-old-website/Dockerfile
    #    image: phober-old-website
    #    container_name: old-website
    #    ports:
    #        - 80:80
    #    volumes:
    #        - ./old-website:/usr/share/nginx/html
    #    networks:
    #        - backend
    #        - frontend

    #website:
    #    build:
    #        context: ./
    #        dockerfile: ./env/phober-website/Dockerfile
    #    image: phober-website
    #    container_name: website
    #    ports:
    #        - 3030:3000
    #    volumes:
    #        - ./website:/app
    #    stdin_open: true
    #    environment:
    #        - CHOKIDAR_USEPOLLING=true
    #    command: npm run start
    #    networks:
    #        - backend
    #        - frontend

volumes:
    dbdata:

networks:
    backend:
        name: phober_backend
        driver: bridge
    frontend:
        name: phober_frontend
        driver: bridge