name: phober-migration

x-php-image: &php-image abdukhaligov/phober-php-apache:2.0.0

# ──────────────────────────────────────────────────────────────────────────────
# Services
# ──────────────────────────────────────────────────────────────────────────────

services:
    db-migration:
        image: *php-image
        container_name: db-migration
        restart: "no"
        env_file:
            - docker/env/laravel.env
            - docker/env/db-auth-admin.env
            - docker/env/db-device-admin.env
            - docker/env/db-crm-admin.env
            - docker/env/db-staff-admin.env
            - docker/env/db-configs-admin.env
            - docker/env/db-shared-admin.env
        environment:
            APP_KEY: ${APP_KEY_DB_MIGRATION}
            DB_CONNECTION: sqlite
        volumes:
            - ./services/db-migration:/var/www/html
        networks: [private]

networks:
    private:
        external: true
        name: phober_private
