name: phober-dozzle

services:
    dozzle:
        image: amir20/dozzle:latest
        container_name: dozzle
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            DOZZLE_FILTER: "name=adminpanel|auth-server|config-server|notification-server|device-service|crm-service|staff-service|notification-queue|staff-queue|device-queue|device-schedule|ws"
            DOZZLE_LEVEL: debug
            DOZZLE_NO_ANALYTICS: "true"
        networks: [public, private]

networks:
    private:
        external: true
        name: phober_private
    public:
        external: true
        name: phober_public
