CREATE DATABASE IF NOT EXISTS phober_adminpanel;
CREATE DATABASE IF NOT EXISTS phober_auth;
CREATE DATABASE IF NOT EXISTS phober_crm;
CREATE DATABASE IF NOT EXISTS phober_notification;
CREATE DATABASE IF NOT EXISTS phober_shared;
