CREATE DATABASE IF NOT EXISTS phober_adminpanel;
CREATE DATABASE IF NOT EXISTS phober_auth;
CREATE DATABASE IF NOT EXISTS phober_device;
CREATE DATABASE IF NOT EXISTS phober_media;
CREATE DATABASE IF NOT EXISTS phober_crm;
CREATE DATABASE IF NOT EXISTS phober_staff;
CREATE DATABASE IF NOT EXISTS phober_notification;
CREATE DATABASE IF NOT EXISTS phober_config;