CREATE DATABASE IF NOT EXISTS phober_shared;
CREATE DATABASE IF NOT EXISTS phober_auth;
CREATE DATABASE IF NOT EXISTS phober_device;
CREATE DATABASE IF NOT EXISTS phober_crm;
CREATE DATABASE IF NOT EXISTS phober_staff;
CREATE DATABASE IF NOT EXISTS phober_configs;
CREATE DATABASE IF NOT EXISTS phober_admin;
